services:
  postgres_db:
    image: postgres:12
    container_name: postgres_general_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
        - mynetwork


  mongo_db:
    image: mongo:4.2
    container_name: mongo_general_db
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
        - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge