spring:
  application:
  name: General Learning Application
  #DataSource related configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/general_db
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
        uri: mongodb://localhost:27017/general_socio?authSource=admin

# GitHub OAuth2 configuration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lieKdxBXtAX
            client-secret: 972a30d36363cc36e3946bba7152e550
            scope: read:user, user:email

# Swagger Documentation configuration
springdoc:
  api-docs:
    path: /api-docs

# Server port configuration
server:
  port: 8024

# Logging configuration
logging:
  level:
    root: info



# News Scrapping Credentials and URL
# News https://newsapi.org/docs/get-started
news:
  api:
    url: https://newsapi.org/v2/everything   #https://newsdata.io/api/1/news
    key: 677*********    #pub_750739195

# Facebook webhook configuration
social:
  config:
    verify_token: gouricreation_24@August